title: Emulator example configuration file.

device: "cuda:0"

june_configuration_file: "./configs/june.yaml"

emulator_configuration:
  time_stamps: [-1]
  save_path: "./data/emulator.pkl"
  samples_path: "./data/samples.pkl"
