title: Emulator example configuration file.

device: "cuda:0"

june_configuration_file: "/home/arnau/code/torch_june_inference/configs/june_config.yaml"

emulator_configuration:
  time_stamps: [-1]
  save_path: "data/emulator.pkl"
  samples_path: "/home/arnau/code/torch_june_inference/data/samples.pkl"
