title: Gradient descent configuration file.

device: "cuda:2"

june_configuration_file: "./configs/june_small.yaml"

results_path: "./results/gradient_descent"

inference_configuration:
  optimizer:
    type: Adam
    lr: 0.0005
    betas: [0.95, 0.999]
    milestones: []
    gamma: 0.2
  n_epochs: 100000
  loss:
    type: MSELoss
    reduction: sum

parameters_to_fit:
  model.infection_networks.networks.leisure.log_beta:
    prior:
      dist: Normal
      loc: 1.0
      scale: 0.5

emulator:
  use_emulator: false

data:
  observed_data: "./results/june/results.csv"
  observable: 
    daily_deaths_by_district:
      time_stamps: [-1]
      error: 0.05

