title: Gradient descent configuration file.

device: "cuda:2"

june_configuration_file: "./configs/june_small.yaml"

results_path: "./results/gradient_descent"

inference_configuration:
  optimizer:
    type: Adam
    lr: 0.0005
    betas: [0.95, 0.999]
    milestones: []
    gamma: 0.2
  n_epochs: 100000
  loss:
    type: MSELoss
    reduction: sum

parameters_to_fit:
  infection_networks.networks.household.log_beta:
    prior:
      dist: Normal
      loc: 1.0
      scale: 0.5
  infection_networks.networks.school.log_beta:
    prior:
      dist: Normal
      loc: 1.0
      scale: 0.5

emulator:
  use_emulator: false

data:
  observed_data: "./results/june/results.csv"
  observable: 
    cases_per_timestep:
      time_stamps: [-1]
      error: 0.00001

