title: MultiNest example configuration file.

june_configuration_file: "/Users/arnull/code/torch_june_inference/configs/june_config.yaml"

results_path: "./test_multinest"

parameters_to_fit:
  infection_passing.log_beta_household:
    prior:
      dist: Uniform
      low: -0.5
      high: 0.5
  infection_passing.log_beta_company:
    prior:
      dist: Uniform
      low: -0.5
      high: 0.5
  infection_passing.log_beta_school:
    prior:
      dist: Uniform
      low: -0.5
      high: 0.5

data:
  observable: cases_per_timestep
  time_stamps: [10, 30, 60, 90]
  observed_data: "/Users/arnull/code/torch_june_inference/data/example.csv"

likelihood:
  distribution: Normal
  error: 0.05
