title: MultiNest example configuration file.

june_configuration_file: "/Users/arnull/code/torch_june_inference/confis/june_config.yaml"

results_path: "./test_multinest"

parameters_to_fit:
  log_beta_household:
    prior:
      dist: Uniform
      low: -1.0
      high: 0.0
  log_beta_company:
    prior:
      dist: Uniform
      low: -1.0
      high: 0.0
  log_beta_school:
    prior:
      dist: Uniform
      low: -1.0
      high: 0.0

likelihood:
  observable: normalized_cases
  time_stamps: [10, 30, 60, 90]
  dist: Normal
  error: 0.05
