title: Pyro example configuration file.

device: "cpu"
june_configuration_file: "./configs/june_config.yaml"

results_path: "./pyro_tests"

inference_configuration:
  kernel: 
    type: NUTS
    max_tree_depth: 5
  num_samples: 5000
  warmup_steps: 1000

parameters_to_fit:
  infection_networks.networks.household.log_beta:
    prior:
      dist: Uniform
      low: -0.25
      high: 0.25
  infection_networks.networks.company.log_beta:
    prior:
      dist: Uniform
      low: -0.25
      high: 0.25
  infection_networks.networks.school.log_beta:
    prior:
      dist: Uniform
      low: -0.25
      high: 0.25

emulator:
  use_emulator: false
  emulator_config_path: "./configs/emulator_cosma.yaml"
  emulator_path: "./data/emulator.path"

data:
  observable: 
    cases_by_age_18:
      time_stamps: [10, 20, 30]
    cases_by_age_25:
      time_stamps: [10, 20, 30]
    cases_by_age_65:
      time_stamps: [10, 20, 30]
    cases_by_age_80:
      time_stamps: [10, 20, 30]
    cases_by_age_100:
      time_stamps: [10, 20, 30]
  observed_data: "./june_example/results.csv"

likelihood:
  distribution: Normal
  error: 0.025

