title: Pyro example configuration file.

device: "cpu"
june_configuration_file: "/Users/arnull/code/torch_june_inference/configs/june_config.yaml"

results_path: "./pyro_tests"

inference_configuration:
  kernel:
    type: NUTS
    max_tree_depth: 5
  num_samples: 5000
  warmup_steps: 100

parameters_to_fit:
  infection_passing.log_beta_household:
    prior:
      dist: Normal
      loc: 0.0
      scale: 0.1

emulator:
  use_emulator: true
  emulator_config_path: "./configs/emulator.yaml"
  emulator_path: "./data/emulator.path"

data:
  observable: cases_per_timestep
  time_stamps: [-1]
  observed_data: "/Users/arnull/code/torch_june_inference/example/results.csv"

likelihood:
  distribution: Normal
  error: 0.005
