n_samples: 250
parameters_to_vary:
  infection_passing.log_beta_household: [-1,1]


june_configuration_file: "/Users/arnull/code/torch_june_inference/configs/june_config.yaml"
save_path: "/Users/arnull/code/torch_june_inference/data/samples.pkl"

