n_samples: 30
n_samples_per_parameter: 10
parameters_to_vary:
  infection_networks.networks.household.log_beta: [-3,3]

june_configuration_file: "/Users/arnull/code/torch_june_inference/configs/june_config.yaml"
save_path: "/Users/arnull/code/torch_june_inference/data/samples.pkl"

