title: SVI example configuration file.

device: "cpu"
june_configuration_file: "./configs/june_small.yaml"

results_path: "./results"

inference_configuration:
  optimizer:
    type: Adam
    lr: 0.01
  n_steps: 10000
  loss:
    type: Trace_ELBO
    num_particles: 10

parameters_to_fit:
  infection_networks.networks.household.log_beta:
    prior:
      dist: Normal
      loc: 0.3
      scale: 0.1

emulator:
  use_emulator: false 
    #emulator_config_path: "./configs/emulator.yaml"
  emulator_path: "./data/emulator.pkl"

data:
  observable: 
    cases_per_timestep:
      time_stamps: "all"
      error: 0.002
    
  observed_data: "./results/june/results.csv"
