title: SVI example configuration file.

device: "cpu"
june_configuration_file: "./configs/june_small.yaml"

results_path: "./results"

inference_configuration:
  optimizer:
    type: Adam
    lr: 0.005
      #betas: [0.95, 0.999]
    milestones: [5000, 10000, 15000]
    gamma: 0.1
  n_steps: 100000
  loss:
    type: Trace_ELBO 
    num_particles: 1

parameters_to_fit:
  infection_networks.networks.household.log_beta:
    prior:
      dist: Normal
      loc: 1.5
      scale: 0.2

emulator:
  use_emulator: false 
    #emulator_config_path: "./configs/emulator.yaml"
  emulator_path: "./data/emulator.pkl"

data:
  observable: 
    cases_per_timestep:
      time_stamps: "all"
      error: 0.001
    
  observed_data: "./results/june/results.csv"
