title: UltraNest example configuration file.

device: "cuda:0"
june_configuration_file: "./configs/june_small.yaml"

results_path: "./results/ultranest"

parameters_to_fit:
  infection_networks.networks.household.log_beta:
    prior:
      dist: Normal
      loc: 0.3
      scale: 0.1
        #infection_networks.networks.company.log_beta:
        #  prior:
        #    dist: Normal
        #    loc: 0.1
        #    scale: 0.1
  infection_networks.networks.school.log_beta:
    prior:
      dist: Normal
      loc: 0.1
      scale: 0.1

data:
  observed_data: "./results/june/results.csv"
  observable: 
    cases_per_timestep:
      time_stamps: [-1]
      error: 0.002

emulator:
  use_emulator: no
  emulator_path: "./data/emulator.pkl"

inference_configuration:
  likelihood: Normal
